import type { ServiceDefinition, ServiceId } from "./types";

export const serviceCatalog: ServiceDefinition[] = [
  {
    id: "global-gateway",
    name: "全局能力网关",
    product: "Caddy",
    description: "统一承接模型、MCP、RAG、Runtime、Connector、知识库与可观测入口。",
    group: "gateway",
    endpointEnv: "GLOBAL_GATEWAY_URL",
    defaultEndpoint: "http://localhost:8080",
    version: "2.11.4",
    probe: { type: "http", path: "/health" },
    docsUrl: "https://caddyserver.com/docs/",
    capabilities: ["统一工具入口", "流式反向代理", "路径与域名隔离"],
  },
  {
    id: "agent-runtime",
    name: "Agent Runtime",
    product: "PydanticAI + FastAPI",
    description: "承载 Agent 运行、审批和工具编排。",
    group: "runtime",
    endpointEnv: "AGENT_RUNTIME_URL",
    defaultEndpoint: "http://runtime.localhost:8080",
    version: "2.12.x",
    probe: { type: "http", path: "/health" },
    docsUrl: "https://ai.pydantic.dev/",
    capabilities: ["Agent 运行", "结构化输出", "审批流程"],
  },
  {
    id: "mcp-access-gateway",
    name: "MCP 访问网关",
    product: "Go + OIDC",
    description: "为兼容 OAuth 的 MCP 客户端提供身份感知访问接口。",
    group: "gateway",
    endpointEnv: "MCP_PUBLIC_RESOURCE_URL",
    defaultEndpoint: "http://localhost:8080/mcp",
    version: "0.1.0",
    probe: {
      type: "http",
      path: "/ready",
      endpointEnv: "MCP_ACCESS_GATEWAY_URL",
      defaultEndpoint: "http://mcp-access-gateway:8081",
    },
    docsUrl: "https://modelcontextprotocol.io/specification/2025-06-18/basic/authorization",
    capabilities: ["OIDC Access Token", "身份绑定会话", "Envoy MCP 代理"],
  },
  {
    id: "llm-gateway",
    name: "大模型网关",
    product: "Envoy AI Gateway",
    description: "只提供外部大模型协议转换、模型路由和流式转发。",
    group: "model",
    endpointEnv: "LLM_GATEWAY_URL",
    defaultEndpoint: "http://localhost:8080/v1",
    version: "1.0.0",
    probe: {
      type: "http",
      path: "health",
      endpointEnv: "LLM_GATEWAY_ADMIN_URL",
      defaultEndpoint: "http://localhost:8080/llm-admin",
    },
    docsUrl: "https://github.com/envoyproxy/ai-gateway",
    capabilities: ["OpenAI 兼容 API", "多供应商协议转换", "流式转发"],
  },
  {
    id: "open-connector",
    name: "外部连接",
    product: "Open Connector",
    description: "管理 SaaS OAuth、凭证和 Action 执行。",
    group: "connection",
    endpointEnv: "OPEN_CONNECTOR_URL",
    defaultEndpoint: "http://localhost:8080/connector",
    version: "1.2.0",
    probe: { type: "http", path: "health" },
    docsUrl: "https://github.com/oomol-lab/open-connector",
    capabilities: ["OAuth", "Action 目录", "凭证代理"],
  },
  {
    id: "lightrag",
    name: "知识工作台",
    product: "LightRAG",
    description: "提供文档导入、混合检索、知识图谱和 RAG 查询。",
    group: "knowledge",
    endpointEnv: "LIGHTRAG_URL",
    defaultEndpoint: "http://localhost:8080/rag",
    version: "1.4.16",
    probe: { type: "http", path: "health" },
    docsUrl: "https://github.com/HKUDS/LightRAG",
    capabilities: ["混合检索", "知识图谱", "文档索引"],
  },
  {
    id: "rag-mcp",
    name: "RAG MCP",
    product: "Python MCP Adapter",
    description: "将 LightRAG 的只读查询和知识图谱能力封装为内置 MCP 工具。",
    group: "knowledge",
    endpointEnv: "RAG_MCP_URL",
    defaultEndpoint: "http://rag-mcp:8080/mcp",
    version: "1.0.0",
    probe: {
      type: "http",
      path: "/health",
      endpointEnv: "RAG_MCP_HEALTH_URL",
      defaultEndpoint: "http://rag-mcp:8080",
    },
    docsUrl: "https://modelcontextprotocol.io/specification/2025-06-18/server/tools",
    capabilities: ["知识问答", "上下文检索", "知识图谱查询"],
  },
  {
    id: "postgres",
    name: "数据与向量",
    product: "PostgreSQL + pgvector + AGE",
    description: "统一保存控制面状态、向量索引和知识图谱。",
    group: "data",
    version: "17 + 0.8.5 + 1.7.0",
    probe: { type: "tcp", hostEnv: "POSTGRES_HOST", portEnv: "POSTGRES_PORT" },
    docsUrl: "https://github.com/pgvector/pgvector",
    capabilities: ["运行元数据", "向量检索", "图数据"],
  },
  {
    id: "promptfoo",
    name: "评测门禁",
    product: "Promptfoo",
    description: "通过按需 Docker/CI 运行回归、安全和红队评测。",
    group: "quality",
    version: "0.121.19",
    probe: { type: "manual" },
    docsUrl: "https://github.com/promptfoo/promptfoo",
    capabilities: ["回归评测", "红队测试", "发布门禁"],
  },
  {
    id: "jaeger",
    name: "链路追踪",
    product: "OpenTelemetry + Jaeger",
    description: "统一查看 Agent、模型、检索和工具调用链路。",
    group: "observability",
    endpointEnv: "JAEGER_URL",
    defaultEndpoint: "http://jaeger:16686",
    version: "2.19.0",
    probe: { type: "http", path: "api/services" },
    docsUrl: "https://www.jaegertracing.io/docs/",
    capabilities: ["Trace", "延迟分析", "故障定位"],
  },
];

export const serviceById = Object.fromEntries(
  serviceCatalog.map((service) => [service.id, service]),
) as Record<ServiceId, ServiceDefinition>;

export function getServiceDefinition(id: string) {
  return serviceCatalog.find((service) => service.id === id);
}
