import type { ServiceDefinition, ServiceId } from "./types";

export const serviceCatalog: ServiceDefinition[] = [
  {
    id: "agent-runtime",
    name: "Agent Runtime",
    product: "PydanticAI + FastAPI",
    description: "承载 Agent 运行、审批和工具编排。",
    group: "runtime",
    endpointEnv: "AGENT_RUNTIME_URL",
    defaultEndpoint: "http://localhost:18000",
    version: "2.12.x",
    probe: { type: "http", path: "/health" },
    docsUrl: "https://ai.pydantic.dev/",
    capabilities: ["Agent 运行", "结构化输出", "审批流程"],
  },
  {
    id: "llm-gateway",
    name: "大模型网关",
    product: "Envoy AI Gateway",
    description: "只提供外部大模型协议转换、模型路由和流式转发。",
    group: "model",
    endpointEnv: "LLM_GATEWAY_URL",
    defaultEndpoint: "http://localhost:8080",
    version: "1.0.0",
    probe: {
      type: "http",
      path: "/health",
      endpointEnv: "LLM_GATEWAY_ADMIN_URL",
      defaultEndpoint: "http://localhost:1064",
    },
    docsUrl: "https://github.com/envoyproxy/ai-gateway",
    capabilities: ["OpenAI 兼容 API", "多供应商协议转换", "流式转发"],
  },
  {
    id: "open-connector",
    name: "外部连接",
    product: "Open Connector",
    description: "管理 SaaS OAuth、凭证和 Action 执行。",
    group: "connection",
    endpointEnv: "OPEN_CONNECTOR_URL",
    defaultEndpoint: "http://localhost:3100",
    version: "1.2.0",
    probe: { type: "http", path: "/health" },
    docsUrl: "https://github.com/oomol-lab/open-connector",
    capabilities: ["OAuth", "Action 目录", "凭证代理"],
  },
  {
    id: "silverbullet",
    name: "知识工作台",
    product: "SilverBullet",
    description: "为员工提供 Markdown、双向链接和知识审阅。",
    group: "knowledge",
    endpointEnv: "SILVERBULLET_URL",
    defaultEndpoint: "http://localhost:3001",
    version: "2.9.0",
    probe: { type: "http", path: "/.ping" },
    docsUrl: "https://github.com/silverbulletmd/silverbullet",
    capabilities: ["Markdown", "双向链接", "知识空间"],
  },
  {
    id: "postgres",
    name: "数据与向量",
    product: "PostgreSQL + pgvector",
    description: "保存控制面状态、审计、全文与向量索引。",
    group: "data",
    version: "17 + 0.8.5",
    probe: { type: "tcp", hostEnv: "POSTGRES_HOST", portEnv: "POSTGRES_PORT" },
    docsUrl: "https://github.com/pgvector/pgvector",
    capabilities: ["运行元数据", "全文检索", "向量检索"],
  },
  {
    id: "promptfoo",
    name: "评测门禁",
    product: "Promptfoo",
    description: "通过按需 Docker/CI 运行回归、安全和红队评测。",
    group: "quality",
    version: "0.121.19",
    probe: { type: "manual" },
    docsUrl: "https://github.com/promptfoo/promptfoo",
    capabilities: ["回归评测", "红队测试", "发布门禁"],
  },
  {
    id: "jaeger",
    name: "链路追踪",
    product: "OpenTelemetry + Jaeger",
    description: "统一查看 Agent、模型、检索和工具调用链路。",
    group: "observability",
    endpointEnv: "JAEGER_URL",
    defaultEndpoint: "http://localhost:16686",
    version: "2.19.0",
    probe: { type: "http", path: "/" },
    docsUrl: "https://www.jaegertracing.io/docs/",
    capabilities: ["Trace", "延迟分析", "故障定位"],
  },
];

export const serviceById = Object.fromEntries(
  serviceCatalog.map((service) => [service.id, service]),
) as Record<ServiceId, ServiceDefinition>;

export function getServiceDefinition(id: string) {
  return serviceCatalog.find((service) => service.id === id);
}
